name: Build Txray

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64, arm64, arm]
        exclude:
          - os: windows
            arch: arm64
          - os: windows
            arch: arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24  # 改成和 go.mod 一致

      - name: Set GOPROXY
        run: go env -w GOPROXY=https://goproxy.cn,direct

      - name: Download dependencies
        run: go mod tidy

      - name: Build for ${{ matrix.os }}/${{ matrix.arch }}
        run: |
          echo "Building for ${{ matrix.os }}/${{ matrix.arch }}"

          ext=""
          if [ "${{ matrix.os }}" = "windows" ]; then
            ext=".exe"
          fi

          mkdir -p build
          go build -o build/Txray-${{ matrix.os }}-${{ matrix.arch }}$ext Txray.go
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
          GOARM: ${{ matrix.arch == 'arm' && '7' || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Txray-${{ matrix.os }}-${{ matrix.arch }}
          path: build/Txray-${{ matrix.os }}-${{ matrix.arch }}*
